project:
  type: website
  output-dir: docs

website:
  title: "STA5073Z"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: assignment2.qmd
        text: Assignment Submission
      - href: llm.qmd
        text: "Using ChatGPT as an LLM"

format:
  html:
    theme: cosmo
    toc: true
